### ISSUE TITLE
Update gif for depsdev README

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#1]
https://github.com/edoardottt/depsdev

Update the depsdev [GIF](https://github.com/edoardottt/images/blob/main/depsdev/depsdev.gif) using the latest depsdev version.

**Comment by carlospatinos** [comment]
Can you assign this to me please? Happy to take it

**Comment by edoardottt** [comment]
For sure @carlospatinos !

In my opinion the best would be using [`charmbracelet/vhs`](https://github.com/charmbracelet/vhs) tool to customize the GIF. 

- The GIF must reproduce the exact same commands you can see on the GIF now
- I'm releasing version `depsdev v0.0.6`, so be sure to install that version (this change the output --> this means try the commands in your terminal before creating the GIF and source .tape file)

Be sure to add here both the .tape and the GIF file.

**Comment by carlospatinos** [comment]
Thanks, just to confirm this is the package right? https://github.com/edoardottt/depsdev and to install that I need go and build that for my platform. Do you know if it supports Mac? I saw the Makefile and saw Linux, Unix, Etc but not Mac specific, just checking before building things. Thanks

**Comment by edoardottt** [comment]
> Do you know if it supports Mac?

You can use the go installer 
```console
go install github.com/edoardottt/depsdev@latest
```

One more time, be sure to download the version `v0.0.6`, I'll release that in some minutes

**Comment by carlospatinos** [comment]
The vhs tool is amazing, using the version you indicated v0.0.6
Any particular config for vhs? font and size of the terminal? Thanks

**Comment by edoardottt** [comment]
> Any particular config for vhs? font and size of the terminal?

Honestly I've used that tool just one time and I don't remember what can be configured, anyway the vast majority of the `.tape` file is the actual commands and outputs in the terminal. We can think to those settings later :)

**Comment by carlospatinos** [comment]
I have something ready I will submit a PR later so you can take a look

**Comment by edoardottt** [comment]
Thanks @carlospatinos ! :)
