### ISSUE TITLE
Update cariddi GIF width and heigth

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#13]
Update GIF width and heigth for cariddi repo

Set Width 1200
Set Height 600

**Comment by edoardottt** [comment]
cc @PaolaDaft, if u want.. **otherwise for all the people reading just comment to be assigned**

**Comment by PaolaDaft** [comment]
I can do it

**Comment by edoardottt** [comment]
amazing @PaolaDaft

**Comment by edoardottt** [comment]
Completed, thanks @PaolaDaft !
