### ISSUE TITLE
Add GIF for favirecon

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#3]
https://github.com/edoardottt/favirecon

Use [`charmbracelet/vhs`](https://github.com/charmbracelet/vhs) to customize the GIF. 

- The GIF must reproduce the command `favirecon -l targets.txt`
- The input file must be a long input file containing different online running services
- Be sure to add here both the .tape and the GIF file.

Let me know if you need some guidance :)

**Comment by carlospatinos** [comment]
If you are happy with the list in the csprecon i can take this and use the same list

**Comment by carlospatinos** [comment]
@edoardottt if you are happy I can take this too

**Comment by edoardottt** [comment]
@carlospatinos it's okay, let's see how diverse are the results

**Comment by edoardottt** [comment]
Completed, thanks @carlospatinos ! See also https://github.com/edoardottt/favirecon/issues/140
