### ISSUE TITLE
Update GIF for cariddi

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#4]
https://github.com/edoardottt/cariddi

Use [`charmbracelet/vhs`](https://github.com/charmbracelet/vhs) to customize the GIF. 

- The GIF must reproduce the exact same commands you can see on the GIF now
- Be sure to add here both the .tape and the GIF file.

Let me know if you need some guidance :)

**Comment by PaolaDaft** [comment]
Can you assign me this one too?

**Comment by edoardottt** [comment]
Done @PaolaDaft !

**Comment by edoardottt** [comment]
Completed, thanks @PaolaDaft !
