### ISSUE TITLE
Update GIF for scilla

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#5]
https://github.com/edoardottt/scilla

Use [`charmbracelet/vhs`](https://github.com/charmbracelet/vhs) to customize the GIF. 

- The GIF must reproduce the exact same commands you can see on the GIF now
- Be sure to add here both the .tape and the GIF file.

Let me know if you need some guidance :)

**Comment by PaolaDaft** [comment]
Can you assign it to me?

**Comment by edoardottt** [comment]
Sure @PaolaDaft ! 

This is similar to https://github.com/edoardottt/images/issues/1, ping me here if you have any doubt

**Comment by PaolaDaft** [comment]
Wow I've never used vhs before and I really like the tool.
To send my changes should I do it in the images/scilla folder, delete the current scilla.gif or add the new one with another name?

**Comment by edoardottt** [comment]
You can replace the current `scilla.gif` in `images/scilla` with the new one, just be sure to add the vhs source file too (`scilla.tape`)

**Comment by edoardottt** [comment]
Completed, thanks @PaolaDaft !
