### ISSUE TITLE
Update GIF for csprecon

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#6]
https://github.com/edoardottt/csprecon

Use [`charmbracelet/vhs`](https://github.com/charmbracelet/vhs) to customize the GIF. 

- The GIF must reproduce the exact same command you can see on the GIF now
- The input file must be a long input file containing different online running services
- Be sure to add here both the .tape and the GIF file.

Let me know if you need some guidance :)

**Comment by carlospatinos** [comment]
Can I help with this? Just please add the topic to the repo as hacktoberfest

**Comment by edoardottt** [comment]
Sure @carlospatinos

**Comment by carlospatinos** [comment]
Thanks

**Comment by carlospatinos** [comment]
Any specific content in the csprecon -l targets.txt ?

**Comment by edoardottt** [comment]
No, the only important thing is that it must contain URLs that produce different results (not ALL different, it's just to avoid that the vast majority produce the same output)

**Comment by edoardottt** [comment]
Completed, thanks @carlospatinos !
