### ISSUE TITLE
Update GIF for pwdsafety

### ISSUE THREAD

**Issue by edoardottt** [edoardottt/images#9]
https://github.com/edoardottt/pwdsafety

Use [`charmbracelet/vhs`](https://github.com/charmbracelet/vhs) to customize the GIF. 

- The GIF must reproduce the exact same commands you can see on the GIF now
- Be sure to add here both the .tape and the GIF file.

Let me know if you need some guidance :)

**Comment by carlospatinos** [comment]
Happy to help you as usual. I can work on that in the next 2 days

**Comment by edoardottt** [comment]
Done @carlospatinos

**Comment by edoardottt** [comment]
Please install it from source https://github.com/edoardottt/pwdsafety#from-source since I've changed the output

**Comment by edoardottt** [comment]
Completed, thanks @carlospatinos !
